sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t marodrigues20/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true marodrigues20/docker-react npm run test